### ISSUE TITLE
Stale timestamps aren't reset

### ISSUE THREAD

**Issue by pjpoole** [markets/invisible_captcha#24]
During some testing, repeatedly refreshing a form I want to use the timestamp captcha on, if the application does not generate a completely new session for each form render from the same browser then the `session[:invisible_captcha_timestamp]` gets fixated on the time of the initial page load.

If a bot loads the form repeatedly using the same session, the timestamp will quickly pass beyond the spam threshold and the throttling will disappear.

**Comment by markets** [comment]
Hi @pjpoole, thanks for reporting!

I think this is because of this (https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/view_helpers.rb#L9-L11):

```
session[:invisible_captcha_timestamp] ||= Time.zone.now.iso8601
```

So the first time the form is rendered, the value is saved and "cached" on the session object. We can easily change that statement to:

```
session[:invisible_captcha_timestamp] = Time.zone.now.iso8601
```

This should avoid the "problem", but then if a real user submits the form and it contains any other error (ie. name is required)... they should wait again for the entire timestamp. So, I'm not sure if it's worth. 

I can take a deeper look asap (probably in a couple of weeks). We can inspect if there is any viable solution resetting that entry (`session[:invisible_captcha_timestamp] = nil`) automatically. Or at least, document how you can solve it by hand:

```
if @user.save
  session[:invisible_captcha_timestamp] = nil
  redirect_to @user
else
  render :new
end
```

Thoughts?

**Comment by pjpoole** [comment]
I found myself at the same line in the source. At first I assumed it was that way just in case someone wants to render multiple invisible captchas in the same controller action, but then I realized that doesn't make a lot of sense. 

From my perspective the purpose of this type of code is to prevent brute-force attacks. So, from an attack mitigation standpoint setting a new time stamp on every captcha'd controller action makes sense - a single brute force tool (i.e. not one being proxied through a dozen endpoints) would have X seconds where it was getting errors, then its attempts would start succeeding, or at least getting through the outer walls. 

As a convenience, humans surely would want to be able to change a typo without having to wait a full X seconds. I'm not sure how to do that without poking a big ol' hole through the security.

**Comment by markets** [comment]
Hi @pjpoole,

> As a convenience, humans surely would want to be able to change a typo without having to wait a full X seconds.

Yes, this is exactly what I thought when I was designing this code... 

But, as you said:

> a single brute force tool (i.e. not one being proxied through a dozen endpoints) would have X seconds where it was getting errors, then its attempts would start succeeding, or at least getting through the outer walls.

this is not ideal, of course, but at this point, I don't have any good idea to fix this without "disturbing" the real users ... Probably we can do something like: resetting the timestamp if the threshold is not reached, as a part of the spam callback (https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/controller_ext.rb#L19)

```ruby
if invisible_captcha_timestamp?(options)
  # threshold not reached, reset the timestamp
  on_timestamp_spam_action(options)
elsif
```

**Comment by dwbutler** [comment]
We use `invisible_captcha` to block user registrations. It usually works pretty well, but sometimes bots still make it through registration and send private messages and post comments on articles. One bot sent 150 private messages in quick succession (spaced one second apart). So I'm now trying to use `invisible_captcha` to guard messaging and comments.

This issue is definitely a blocker for us, because if the bot makes it past the initial invisible captcha during registration it can now send unlimited spam messages. We've worked around the issue in the following way.

In `config/initializers/invisible_captcha.rb`:
```ruby
module InvisibleCaptcha
  module ControllerExt
    def reset_invisible_captcha_timestamp
      session[:invisible_captcha_timestamp] = nil
    end
  end
end
```

In the respective controllers, we manually call `reset_invisible_captcha_timestamp` in the `on_timestamp_spam` callback, and on successful completion of the action. This way, each new message or comment starts off with a fresh timestamp, and the timestamp isn't reset if there's a validation error.

**Comment by markets** [comment]
Thanks @dwbutler! 

Yes, I'm going to provide an internal public method to clean up the timestamp, something similar to your example (and probably call it automatically on the `on_timestamp_spam` callback as well). As I described here: https://github.com/markets/invisible_captcha/pull/26#issuecomment-274336622

Any kind of feedback is really appreciated!

**Comment by markets** [comment]
Hi @pjpoole @dwbutler after revisiting this again, now I'm more inline with the idea of changing the default behaviour. In terms of code: 

Instead of this:

`session[:invisible_captcha_timestamp] ||= Time.zone.now.iso8601`

This:

`session[:invisible_captcha_timestamp] = Time.zone.now.iso8601`

That means, there is no stale timestamps anymore, on each form render the timestamp is regenerated. At the end, it solves more problems than before, and to be honest, nowadays most people are validating stupid forms errors on front-end. Or if they don't do it, the only problem  would be that the user should wait a few seconds (customizable per action) to resubmit . Also, as an advantage, there are no steal timestamps anymore and no need to implement a new public method + docs explaining how to reset the timestamp manually in some cases. So, probably it's worth at this point.

I started to work on this next release here: #32. I'm improving the demo app to easy test and show how these combinations work (`bundle exec rake web` to startup):

![captura de pantalla 2017-12-09 a la s 21 15 30](https://user-images.githubusercontent.com/576701/33799170-7e23251a-dd26-11e7-95b3-80a6453b374b.png)

**Comment by rsiddle** [comment]
@markets I just ran into the same issue here and decided to override the method so it returns a fresh timestamp rather than the stale one. A bot may crawl around on a few webpages before submitting a form. @pjpoole mentioned about typos, we're testing some string similarity algorithms to determine if it is a typo with a degree of confidence.

**Comment by markets** [comment]
hi @rsiddle, yes definitely would be better to serve a fresh timestamp on each form render, since this will be more effective blocking bots. That's already changed in #32 (I'll push a new release this week or during christmas). About the "typos" thing, it won't really dramatic, most of people are doing front-end validations for these kind of things and also, the threshold is customizable per action, so in case you have a short form (which most people probably will complete fast) you can put for that action a small threshold (say 1 or 2 secs).

Thanks for your feedback!
