### ISSUE TITLE
Best practices for testing controllers?

### ISSUE THREAD

**Issue by whatupdave** [markets/invisible_captcha#25]
I'm skipping invisible_captcha for my controller tests, eg:

```
# some_controller.rb
if !Rails.env.test?
  invisible_captcha only: [:create], on_spam: :on_spam_detected
end
```

but I don't like the duplication in each controller, perhaps we could add some kind of noop flag for tests?

**Comment by markets** [comment]
Hi @whatupdave,

If you just want to disable the timestamp check, because you don't want to wait some seconds before hit that endpoint, you can use this flag: `timestamp_enabled`. Related discussion: https://github.com/markets/invisible_captcha/issues/20.

So, in your testing environment config add:

```ruby
InvisibleCaptcha.timestamp_enabled = false
```

There is, actually, no option to completely disable the engine, but the most controversial part (on tests) is probably the timestamp check.

You can also check this PR in another Rails app: https://github.com/consul/consul/pull/1103, as an example of a good integration of the gem.

**Comment by markets** [comment]
Hi @whatupdave, I'm going to close this issue. Using `InvisibleCaptcha.timestamp_enabled = false` you can skip the wait interval. Thanks!
