### ISSUE TITLE
How to verify that it's been set up and is working correctly?

### ISSUE THREAD

**Issue by GildedHonour** [markets/invisible_captcha#31]
How do I verify that it's been  set up and working well? Is there a way to find out the amount of bots it has saved my app from?

**Comment by markets** [comment]
Hi @GildedHonour, if you want to verify your installation, you can do it, for example, by enabling the `visual_honeypots` option, which make the honeypots visible, so you can fill on the input and test your callbacks, settings ... full settings list [here].(https://github.com/markets/invisible_captcha#options-and-customization)

About your second question, directly this gem doesn't do anything related at this point, but since you can use callbacks, you can provide your own behaviour:

````
class TopicsController < ApplicationController
  invisible_captcha only: [:create], on_spam: :my_spam_callback

  private

  def my_spam_callback
    # your logic here, random examples: 
    #   - store in redis: redis.set('topics_create_spam', 1)
    #   - store in app db, create a model: SpamRegistry.create(action: 'topics_create', 1) 
    #   - ...
    redirect_to root_path
  end
end
```

**Comment by rubyrailsninja** [comment]
Hello,

I personaly install invisible_captcha because I had few spam emails who signup to my newsletter form.

I first test to signup without problem
Since installation, I saw less signups but I can observe in rails log/prod when spam has been rejected
