### ISSUE TITLE
[SimpleForm integration] f.input passes validation, when it should not

### ISSUE THREAD

**Issue by rsiddle** [markets/invisible_captcha#34]
Using the example from the docs:

```
<%= f.invisible_captcha :subtitle %>
<%= invisible_captcha :subtitle, :user %>
```

Filling in the honeypot field when attaching to a model appears to pass validation. When using ` <%= invisible_captcha :subtitle %>` it does not pass validation and returns the 200 HEAD response. The form in this example is generated through the [SimpleForm gem](https://github.com/plataformatec/simple_form).

```
# registrations/new.html.erb
<%= simple_form_for(@user, as: :user, url: registration_path(:user), wrapper: :inline_form) do |f| %>
  <%= f.invisible_captcha :subtitle %>
  <%= f.input :email, input_html: { placeholder: 'john@example.com' } %>
<% end %>
```

```
class Users::RegistrationsController < Devise::RegistrationsController
  invisible_captcha only: [:create], honeypot: :subtitle
  ...
end
```

**Comment by markets** [comment]
Hi again @rsiddle, to be honest I never used `InvisibleCaptcha` with `SimpleForm`, so I'm not sure what is needed to make it compatible with their helpers `f.input`. As you said, using the view helper `<%= invisible_captcha :subtitle, :user %>` should work with no problems. So I was never worried about this kind of integrations because of that.

For Rails form helpers, the integration is pretty straightforward, we just delegate to the view layer: https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/form_helpers.rb

```
@template.invisible_captcha(...)
```

I understand SimpleForm is quite used gem, so probably we should make something to improve this situation:
- we can just fix the docs explaining that for SimpleForm integration is preferable the view helper directly instead of the resource oriented helper `f.something`
- or we can also provide official support 

I'd prefer official support if code changes and maintenance costs (think on different SimpleForm versions or problems like this) aren't big. I'll try to take a look in the future, but if you want to help with this would be amazing! 

Thanks.

**Comment by bf39l** [comment]
I think @rsiddle's issue is cause by devise, if you be able to tail development log you may find out the parameters for register post request would looks like 

> {... "user" => {"name" =>"xxx", "your_honeypot"=>"xxx"...}...}
if that's the case you need to add :scope into your controller like

> class Users::RegistrationsController < Devise::RegistrationsController
>   invisible_captcha only: [:create], honeypot: :subtitle, scope: :user
>   ...
> end
hope that can help.

**Comment by markets** [comment]
Thanks @bf39l

There are different ways to make it work with simple_form (as commented in https://github.com/markets/invisible_captcha/issues/34#issuecomment-353174829 too). So finally, I'm going to close this one.
