### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by groe** [markets/invisible_captcha#35]
Hi! Is there a changelog somewhere? Would be very helpful for upgrading existing projects.

**Comment by markets** [comment]
Hi @groe, you're totally right I need to add one, will do it during next days.

Meanwhile, if you need a reference to the latest release: #32 

Thanks for your feedback!

**Comment by groe** [comment]
Great, thanks a lot @markets!

**Comment by markets** [comment]
@groe 👉 https://github.com/markets/invisible_captcha/commit/89f3da811d93dc1c3780c52d7fcb7dc9250024e6

**Comment by changelox** [comment]
Hi @markets, just one question, how have you created your changelog? I'm asking because we are currently working on a service (changelox.com) to make changelog maintenance much easier without being a simple changelog generator. It's free for open source repos and if you're interested in testing it we would appreciate your feedback. :)

**Comment by markets** [comment]
Hi @changelox I used a couple of things to create this first version:

- https://github.com/skywinder/github-changelog-generator 
- http://keepachangelog.com/en/1.0.0/

Then, I reviewed manually the automatically generated stuff and removed some unnecessary (IMO) things. I think I prefer to keep the changelog by hand at this point. Thanks.

**Comment by changelox** [comment]
@markets Cool, never mind and thanks for your quick response! :-)
