### ISSUE TITLE
Errors Using Invisible Captcha - Cannot contact reCAPTCHA. Check your connection and try again

### ISSUE THREAD

**Issue by ArthurZ** [markets/invisible_captcha#36]
Hi there,

Initially, I setup it to work in the minimal form as
```
<%= form_tag(testf_path) do |f| %>
  <%= invisible_captcha %>
<% end %>
```
 And got an error: `may be you meant invisible_recaptcha_tags`
After switching to using `invisible_recaptcha_tags` error
`Cannot contact reCAPTCHA. Check your connection and try again` occurred.
At this point in time unable to implement it.

**Comment by markets** [comment]
Hi @ArthurZ, 

This error isn't caused by this gem at all. This error is raised by another gem installed in your app, I supose: https://github.com/ambethia/recaptcha, because you can find that helper in its repo: https://github.com/ambethia/recaptcha/search?q=invisible_recaptcha_tags&type=Code. 

If you want to use `invisible_captcha` (this one), make sure you have this line in your Gemfile:

    gem 'invisible_captcha'

Thanks!
