### ISSUE TITLE
[Ruby 2.7.0] warn method overrides existing method

### ISSUE THREAD

**Issue by JamesLindstrom** [markets/invisible_captcha#65]
I've recently updated an app to Ruby 2.7.0. Since then I've run into an issue I believe to be caused in part by invisible_captcha.

At a point in a controller, my code requires 'open-uri' and then runs `sitemap = open("#{bucket_path}/index.xml")`. This prompts Ruby to call a warning method like so `warn('calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open', uplevel: 1)`.

For more context, you can find this line on this page, line 18: https://github.com/ruby/ruby/blob/ruby_2_7/lib/open-uri.rb

Where this causes an issue is that the "warn" method defined in invisible_captcha ends up being the one that is called, and seeing as it can only accept 2 arguments, it causes a 500 error.

Yes, I can prevent "warn" from being called by changing my code to `sitemap = URI.open("#{bucket_path}/index.xml")` (which I intend to do anyway), but I'm concerned that this overriding of warn may cause issues when other warnings are raised for other reasons.

**Comment by markets** [comment]
Hi @JamesLindstrom 👋 and thanks a lot for such explanations. Maybe it's caused by this method:

https://github.com/markets/invisible_captcha/blob/fb72c7898f7f0fbf6701f2aa98f4a53e29419334/lib/invisible_captcha/controller_ext.rb#L100

I agree, `warn` seems too much generic name for a method that is injected in all Rails controllers, maybe we can solve this by just renaming the method to something like `warn_spam`.  Do you want to send a pull request?
