### ISSUE TITLE
first doc example missing :scope param?

### ISSUE THREAD

**Issue by cgs** [markets/invisible_captcha#78]
Couldn't figure out why it wasn't working for my standard Devise implementation. My form with `user` object needed `scope: :user` in the controller call. This is not clear in the docs. Should the example be the following or am I missing something? Happy to submit PR if so.

```
class TopicsController < ApplicationController
  invisible_captcha only: [:create, :update], honeypot: :subtitle, scope: :topic
end
````

**Comment by markets** [comment]
Hi @cgs 👋 this example was fine, the reason is: the `scope` is inferred from the `controller_name`, so in regular REST resources (like the "topics" example) will work just fine:

https://github.com/markets/invisible_captcha/blob/7fba3a13a6e6e359be8f1d78ea672dd5b9c7a224/lib/invisible_captcha/controller_ext.rb#L80

The point is, in Devise the controller is not UsersController, should be something like RegistrationsController, so the default `scope` (via `controller_name`) is not the one you are looking for.

Maybe we can just clarify this a bit in the docs? Probably, I'd expand a bit the `scope` explanation here https://github.com/markets/invisible_captcha#controller-method-options.

PS Remember, you can also use the invisible_captcha helper with no arguments, which will use the "default honeypots" and then your controller doesn't need to know about the scope.
