### ISSUE TITLE
Potential spam detected for IP  Invisible Captcha timestamp not found in session.

### ISSUE THREAD

**Issue by Legomegger** [markets/invisible_captcha#79]
Hi, thanks for your gem. I've got an problem. I did insert **<%= invisible_captcha %> to login.html.erb,** and **invisible_captcha** in account controller:  **invisible_captcha only: [:login], on_spam: :redirect_to_signin**. And when i try to go to the /login, im getting an error, 
`Potential spam detected for IP 10.68.33.1. Invisible Captcha timestamp not found in session.
Completed 500 Internal Server Error in 97ms (ActiveRecord: 65.7ms)

NameError (undefined local variable or method `root_path' for #<AccountController:0x0000000009890ea0>
Did you mean?  robots_path
               role_path
               roles_path):
`

however if i add callback on_timestamp_spam: :noop, the error is gone. Could you help me, what am i doing wrong? Thanks

**Comment by markets** [comment]
Hi @Legomegger 👋🏼 

I think your problem is: in your controller you should add the `invisible_captcha` filter only for the action your form is pointing, now you added `only: [:login]`, which seems the same action you use to render the form => so the gem, which also contains a time sensitive check, is halting your request when visiting the form page. If you don't want to use this feature (time sensitive submissions), you can also disable it (via initializer) by: `config.timestamp_enabled = false`.
