### ISSUE TITLE
Potential spam detected for IP 127.0.0.1. Invisible Captcha timestamp not found in session.

### ISSUE THREAD

**Issue by joshm1204** [markets/invisible_captcha#88]
When I change my form to remote: true, I get the following error:

`Potential spam detected for IP 127.0.0.1. Invisible Captcha timestamp not found in session.`

**Comment by markets** [comment]
Hello @joshm1204, this is weird, I use the `remote: true` + `invisible_captcha` combination in several apps with no problems. The `timestamp` is automatically set up when calling the view helper:

https://github.com/markets/invisible_captcha/blob/8824e31059dd88bb786f4fb0e899aafdff3a5a41/lib/invisible_captcha/view_helpers.rb#L14

So, it seems the helper is not being called in your case, maybe browser cache? maybe some specific js in your app?

**Comment by joshm1204** [comment]
After more testing, it seems to occur after the second submit.  So the first submit after the page load works, but not the second or third.  It seems I may need to reload the form via ajax. Any recommendations how you would handle it?

**Comment by markets** [comment]
Ok! Yep, probably the best way is to re-render the form in the ajax response, since the view helper needs to set the new timestamp in the session, as commented before:

https://github.com/markets/invisible_captcha/blob/8824e31059dd88bb786f4fb0e899aafdff3a5a41/lib/invisible_captcha/view_helpers.rb#L14
