### ISSUE TITLE
Replace Rails dependency with only which Rails gems are actually needed 

### ISSUE THREAD

**Issue by ssunday** [markets/invisible_captcha#93]
Instead of requiring `rails` can it be more specific and require just `actionpack` / `activesupport` for example? So it's not pulling in all of `rails` when that's not needed for this gem to work?

This has come up as an issue during the downstream issue  regarding the `marcel` dependency (a dependency of `activestorage`) `mimemagic`. Even if we're not using `activestorage`, we cannot remove it as `invisible_captcha` depends on Rails in its entirety and pulls it in.

**Comment by markets** [comment]
Hello @ssunday 👋🏼 

Yes! thanks for the ping, I also have followed the thread in Twitter and in the `minad/mimemagic` repo. Not really sure how it ended, but very interesting discussion. I have read a lot of interesting point of views there. Hopefully people will start using more and better caching deps in their CIs and deploys 😄  after that.

The change you are proposing seems very reasonable, even more since Rails is pulling new dependencies on each release and this gem only needs few parts of Rails to work 100% fine (we need Rails as dev dep, but yeah, not as runtime dep).

I'll try take a look asap, but I'm quite busy for at least ~2 weeks with other OSS work too. If someone wants to take a look and send a PR, I'd be happy to review it.

Best,
Marc

**Comment by ssunday** [comment]
Thanks! I might raise a PR myself if/when I get the chance.
